-- MySQL Script generated by MySQL Workbench
-- Mon Jul 24 16:57:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ts_trasporti
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ts_trasporti
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ts_trasporti` DEFAULT CHARACTER SET utf8 ;
USE `ts_trasporti` ;

-- -----------------------------------------------------
-- Table `ts_trasporti`.`Passeggero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ts_trasporti`.`Passeggero` (
  `idPasseggero` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `cognome` VARCHAR(45) NULL,
  `dataNascita` DATE NULL,
  `residenza` VARCHAR(45) NULL,
  `città` VARCHAR(45) NULL,
  `telefono` CHAR(10) NULL,
  `metodoPagamento` CHAR(1) NULL,
  `numeroCarta` CHAR(16) NULL,
  `scadenzaCarta` CHAR(5) NULL,
  `CVV` CHAR(3) NULL,
  `CF` CHAR(16) NULL,
  PRIMARY KEY (`idPasseggero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts_trasporti`.`Autista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ts_trasporti`.`Autista` (
  `idAutista` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `cognome` VARCHAR(45) NULL,
  `dataNascita` DATE NULL,
  `residenza` VARCHAR(45) NULL,
  `città` VARCHAR(45) NULL,
  `telefono` CHAR(10) NULL,
  `dataAssunzione` DATE NULL,
  `dataScadenzaConstratto` DATE NULL,
  `IBAN` CHAR(27) NULL,
  `stipendio` INT NULL,
  PRIMARY KEY (`idAutista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts_trasporti`.`Ufficio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ts_trasporti`.`Ufficio` (
  `idUfficio` INT NOT NULL AUTO_INCREMENT,
  `indirizzo` VARCHAR(45) NULL,
  `città` VARCHAR(45) NULL,
  `provincia` CHAR(2) NULL,
  `CAP` CHAR(5) NULL,
  PRIMARY KEY (`idUfficio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts_trasporti`.`Dipendente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ts_trasporti`.`Dipendente` (
  `idDipendente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `cognome` VARCHAR(45) NULL,
  `dataNascita` DATE NULL,
  `residenza` VARCHAR(45) NULL,
  `città` VARCHAR(45) NULL,
  `telefono` CHAR(10) NULL,
  `dataAssunzione` DATE NULL,
  `dataScadenzaContratto` DATE NULL,
  `IBAN` CHAR(27) NULL,
  `livello` CHAR(1) NULL,
  `stipendio` INT NULL,
  `ufficio` INT NULL,
  PRIMARY KEY (`idDipendente`),
  INDEX `ufficio_idx` (`ufficio` ASC) VISIBLE,
  CONSTRAINT `ufficio`
    FOREIGN KEY (`ufficio`)
    REFERENCES `ts_trasporti`.`Ufficio` (`idUfficio`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts_trasporti`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ts_trasporti`.`Account` (
  `idAccount` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `utente` INT NULL,
  PRIMARY KEY (`idAccount`),
  INDEX `utente_idx` (`utente` ASC) VISIBLE,
  CONSTRAINT `autista`
    FOREIGN KEY (`utente`)
    REFERENCES `ts_trasporti`.`Autista` (`idAutista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dipendente`
    FOREIGN KEY (`utente`)
    REFERENCES `ts_trasporti`.`Dipendente` (`idDipendente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `passeggero`
    FOREIGN KEY (`utente`)
    REFERENCES `ts_trasporti`.`Passeggero` (`idPasseggero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts_trasporti`.`Linea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ts_trasporti`.`Linea` (
  `idLinea` INT NOT NULL AUTO_INCREMENT,
  `denominazione` VARCHAR(3) NULL,
  PRIMARY KEY (`idLinea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts_trasporti`.`Mezzo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ts_trasporti`.`Mezzo` (
  `idMezzo` INT NOT NULL AUTO_INCREMENT,
  `targa` CHAR(7) NULL,
  `postiDisponibili` INT NULL,
  `autista` INT NULL,
  `linea` INT NULL,
  PRIMARY KEY (`idMezzo`),
  INDEX `linea_idx` (`linea` ASC) VISIBLE,
  INDEX `autista_idx` (`autista` ASC) VISIBLE,
  CONSTRAINT `linea`
    FOREIGN KEY (`linea`)
    REFERENCES `ts_trasporti`.`Linea` (`idLinea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `autistaMezzo`
    FOREIGN KEY (`autista`)
    REFERENCES `ts_trasporti`.`Autista` (`idAutista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts_trasporti`.`Fermata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ts_trasporti`.`Fermata` (
  `idFermata` INT NOT NULL AUTO_INCREMENT,
  `indirizzo` VARCHAR(45) NULL,
  `riferimento` VARCHAR(45) NULL,
  PRIMARY KEY (`idFermata`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts_trasporti`.`Tratta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ts_trasporti`.`Tratta` (
  `idTratta` INT NOT NULL AUTO_INCREMENT,
  `costo` FLOAT(4,2) NULL,
  PRIMARY KEY (`idTratta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts_trasporti`.`Composizione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ts_trasporti`.`Composizione` (
  `pkComposizione` INT NOT NULL,
  PRIMARY KEY (`pkComposizione`),
  CONSTRAINT `tratta`
    FOREIGN KEY (`pkComposizione`)
    REFERENCES `ts_trasporti`.`Tratta` (`idTratta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fermataPartenza`
    FOREIGN KEY (`pkComposizione`)
    REFERENCES `ts_trasporti`.`Fermata` (`idFermata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fermataArrivo`
    FOREIGN KEY (`pkComposizione`)
    REFERENCES `ts_trasporti`.`Fermata` (`idFermata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts_trasporti`.`Viaggio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ts_trasporti`.`Viaggio` (
  `idViaggio` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NULL,
  `oraPartenza` CHAR(5) NULL,
  `oraArrivo` CHAR(5) NULL,
  `linea` INT NULL,
  `tratta` INT NULL,
  PRIMARY KEY (`idViaggio`),
  INDEX `linea_idx` (`linea` ASC) VISIBLE,
  INDEX `tratta_idx` (`tratta` ASC) VISIBLE,
  CONSTRAINT `lineaViaggio`
    FOREIGN KEY (`linea`)
    REFERENCES `ts_trasporti`.`Linea` (`idLinea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `trattaViaggio`
    FOREIGN KEY (`tratta`)
    REFERENCES `ts_trasporti`.`Tratta` (`idTratta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts_trasporti`.`Prenotazione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ts_trasporti`.`Prenotazione` (
  `idPrenotazione` INT NOT NULL AUTO_INCREMENT,
  `dataPrenotazione` DATETIME NULL,
  `quantità` INT NULL,
  `viaggio` INT NULL,
  `passeggero` INT NULL,
  PRIMARY KEY (`idPrenotazione`),
  INDEX `viaggio_idx` (`viaggio` ASC) VISIBLE,
  INDEX `passeggero_idx` (`passeggero` ASC) VISIBLE,
  CONSTRAINT `viaggio`
    FOREIGN KEY (`viaggio`)
    REFERENCES `ts_trasporti`.`Viaggio` (`idViaggio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `passeggeroPrenotazione`
    FOREIGN KEY (`passeggero`)
    REFERENCES `ts_trasporti`.`Passeggero` (`idPasseggero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
